### ISSUE TITLE
How to access state?

### ISSUE THREAD

**Issue by sdcaulley** [DanielTurner/lit-state#3]
Wonderful explanation on how to place items in state.  However, there is no explanation on how to get them back out.  Could you please add that to the documentation?

**Comment by DanielTurner** [comment]
@sdcaulley great suggestion, I will tag you again when I add that to the documentation.

**Comment by DanielTurner** [comment]
@sdcaulley I have added the documentation about getting the data back out.
Let me know if this answers your question and I will push the changes to npm also.

Thank you.

**Comment by sdcaulley** [comment]
@DanielTurner Thank you for doing that.  I think I am still missing something.  I can see the state object in both session and local storage, but I am not able to get them back out.  The code I am trying to use the state with looks like this:

```
import { html } from 'lit-element';
import { LitState } from '@danielturner/lit-state';
import { router } from './site-routes.js';

export default class Blog extends LitState {
	static get properties () {
		return {
			location: {
				type: Object,
				attribute: false
			},
			category: { type: String },
			state: { type: Object },
			title: { type: String }
		};
	}

	constructor () {
		super();
		this.location = router.location;
		this.category = '';
		this.title = '';
		this.state = {
			blogItems: [],
			category: ''
		};
	}

	findBlog () {
		console.log('state: ', this.state);
		console.log('title: ', this.title);
		const blogItem = this.state.blogItems.find(item => {
			return item.title === this.title;
		});

		console.log('blogItem: ', blogItem);

		// ....
	}

	render () {
		this.itemId = this.location.params.title;

		this.findBlog();
	}
}

customElements.define('blog-item', Blog);
```

**Comment by DanielTurner** [comment]
@sdcaulley Are you trying to access state directly from localstorage? If so, you don't need to. The purpose of the localstorage is to allow the system to automatically pick it up next time the user re-loads the application.

**Comment by DanielTurner** [comment]
Presuming that this is resolved now @sdcaulley closing the issue.
